name: Deploy Serverless Function to Vercel

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: go mod tidy

    - name: Build the project
      run: go build

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      run: |
        # Install Vercel CLI
        npm install -g vercel
        
        # Deploy to Vercel
        vercel --token $VERCEL_TOKEN --prod --confirm --env HUBSPOT_API_KEY=$HUBSPOT_API_KEY
