name: Deploy Go Cloud Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build the Go function
        run: |
          cd functions
          go mod init github.com/joshbrgs/my-portfolio-api || true
          go mod tidy
          go build -o main

      - name: Configure gcloud CLI
        run: |
          echo ${{ secrets.GCP_PROJECT }} > /tmp/project
          echo ${{ secrets.GCP_SERVICE_ACCOUNT }} > /tmp/service-account

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/582533010918/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Deploy to Google Cloud Functions
        run: |
          gcloud functions deploy CreateHubspotContact \
            --entry-point Handler \
            --runtime go122 \
            --trigger-http \
            --allow-unauthenticated \
            --region us-central1 \
            --source functions/ \
            --gen2
